### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by Kartikexp**
I hope u like it

### CODE REVIEW

**Comment by Kartikexp** [comment]
Hey can u pls merge it or tell me what else can i do to help u

**Comment by Kartikexp** [comment]
Can u pls add the hactoberfest tag to the repository and pls merge my request

**Comment by duymv** [comment]
@Kartikexp 
Hi, Kartikexp.
Thank you for your work at my repository. 
I'm reviewing your PR but see no different in files change. Can you check again your PR and push some update?

**Comment by Kartikexp** [comment]
Sorry I will open another request I guess I messed up:(

**Pull request closed without merging**
